//http://localhost:3000/api/memories/123456

//POST http://localhost:3000/api/users
//Content-Type: application/json

//{
    //"username": "andrew",
    //"password": "Sigma19231."
//}

http://localhost:3000/api/memories